/**
 * Runtime model catalog for the Verboo Code provider.
 *
 * Two layers, never either alone:
 *
 *  1. Build-time generated fallback — `src/catalog.generated.ts`, committed to
 *     the repo and regenerated by `scripts/generate-catalog.ts` from Verboo's
 *     own `/models` endpoint. Every capability number in it traces to that
 *     endpoint, the probe report, or a manual override with a note.
 *
 *  2. Runtime fetch of Verboo's `/models` endpoint. Unlike NaN's endpoint,
 *     Verboo's is capability-rich: it returns `context_window`, `vision`, and
 *     `reasoning.effort_levels`/`default_effort` per model. That makes the live
 *     response the authoritative per-key list, not just a set of IDs.
 *
 * Merge: a live row with generated data keeps the generated capabilities
 * (compat, curated maxTokens, provenance notes); an uncatalogued live row
 * gets its capabilities parsed from the live payload with conservative
 * placeholder `maxTokens` — capabilities stay "unknown", nothing is
 * fabricated. On fetch failure, timeout, or an unusable response, callers
 * fall back to the generated catalog so startup is never blocked.
 */

import type { Model, OpenAICompletionsCompat, ThinkingLevelMap } from "@earendil-works/pi-ai";
import { GENERATED_CATALOG_META, VERBOO_GENERATED_MODELS } from "./catalog.generated.ts";
import { thinkingLevelMapFromEfforts } from "./thinking-levels.ts";

export type { Model };

/**
 * Serializable model definition in the generated fallback catalog
 * (`src/catalog.generated.ts`). Lives here so the generator (`scripts/`) and
 * the runtime share one definition without a circular type alias.
 */
export interface GeneratedModelEntry {
	id: string;
	name: string;
	reasoning: boolean;
	input: ("text" | "image")[];
	cost: { input: number; output: number; cacheRead: number; cacheWrite: number };
	contextWindow: number;
	maxTokens: number;
	/** Per-model pi thinking-level map derived from the Verboo effort levels. */
	thinkingLevelMap?: ThinkingLevelMap;
	/** Gateway compat applied to every Verboo model (probe-measured, see VERBOO_COMPAT). */
	compat?: OpenAICompletionsCompat;
	/** Provenance notes for values Verboo does not publish or that need manual confirmation. */
	notes?: string[];
}

/** pi-ai streaming API used for the Verboo provider. */
export const VERBOO_COMPAT_API = "openai-completions" as const;

/**
 * Verboo gateway compat, MEASURED by `scripts/probe-verboo.ts` against
 * `https://code.verboo.ai/router/v1` and recorded in
 * `scripts/probe-report.json` (2026-09-25). Do not re-litigate:
 *
 * - `thinkingFormat: "openai"`        — Verboo documents `reasoning_effort`;
 * - `supportsReasoningEffort: true`   — `reasoning_effort:"max"` returned 200;
 * - `supportsDeveloperRole: false`    — docs list system|user|assistant|tool;
 * - `maxTokensField: "max_tokens"`    — documented and measured 200;
 * - `supportsFinishReason: true`      — present in stream and non-stream;
 * - `supportsUsageInStreaming: true`  — usage chunk present with and without
 *   `stream_options`, so no payload sanitizer is needed.
 */
export const VERBOO_COMPAT: OpenAICompletionsCompat = {
	thinkingFormat: "openai",
	supportsReasoningEffort: true,
	supportsDeveloperRole: false,
	maxTokensField: "max_tokens",
	supportsFinishReason: true,
	supportsUsageInStreaming: true,
};

/**
 * Conservative limits for a live model with no generated catalog match.
 * A safe request envelope, not a capability claim.
 */
export const UNKNOWN_MODEL_LIMITS = { contextWindow: 128_000, maxTokens: 4_096 } as const;

/** Timeout for the live `/models` fetch, matching the pi-synthetic-provider precedent (~3s). */
export const DEFAULT_MODELS_TIMEOUT_MS = 3_000;

export interface CatalogSource {
	/** Provider id as registered in pi, e.g. "verboo". */
	providerId: string;
	/** OpenAI-compatible base URL including version path, e.g. "https://code.verboo.ai/router/v1". */
	baseUrl: string;
}

/** Convert a generated catalog entry into a pi-ai Model for the given provider. */
export function toModel(
	entry: GeneratedModelEntry,
	source: CatalogSource,
): Model<"openai-completions"> {
	return {
		id: entry.id,
		name: entry.name,
		api: VERBOO_COMPAT_API,
		provider: source.providerId,
		baseUrl: source.baseUrl,
		reasoning: entry.reasoning,
		input: [...entry.input],
		cost: { ...entry.cost },
		contextWindow: entry.contextWindow,
		maxTokens: entry.maxTokens,
		...(entry.thinkingLevelMap ? { thinkingLevelMap: { ...entry.thinkingLevelMap } } : {}),
		...(entry.compat ? { compat: { ...entry.compat } } : {}),
	};
}

/** The generated fallback catalog as pi-ai Models for the given provider. */
export function baselineModels(source: CatalogSource): Model<"openai-completions">[] {
	return VERBOO_GENERATED_MODELS.map((entry) => toModel(entry, source));
}

/**
 * A capability row parsed from Verboo's live `/models` response.
 * Every field except `id` is optional: the parser is tolerant of the
 * endpoint omitting a field, but it never invents one.
 */
export interface LiveModelCapability {
	id: string;
	contextWindow?: number;
	vision?: boolean;
	reasoning?: {
		effortLevels?: string[];
		defaultEffort?: string;
	};
}

export interface LiveModelListOptions {
	baseUrl: string;
	/** Optional bearer key. Verboo's `/models` requires one for a useful listing. */
	apiKey?: string;
	timeoutMs?: number;
	/** Injectable for tests; defaults to global fetch. */
	fetchImpl?: typeof fetch;
}

function isRecord(value: unknown): value is Record<string, unknown> {
	return typeof value === "object" && value !== null;
}

function asNonEmptyString(value: unknown): string | undefined {
	return typeof value === "string" && value.trim().length > 0 ? value.trim() : undefined;
}

function asPositiveNumber(value: unknown): number | undefined {
	return typeof value === "number" && Number.isFinite(value) && value > 0 ? value : undefined;
}

function asStringArray(value: unknown): string[] | undefined {
	if (!Array.isArray(value)) return undefined;
	const out = value.filter((item): item is string => typeof item === "string" && item.length > 0);
	return out.length > 0 ? out : undefined;
}

/**
 * Verboo returns `{ object: "list", data: [...] }` today, but other
 * OpenAI-compatible gateways return `{ models: [...] }` or a bare array.
 * Accept all three so a proxy change does not silently empty the catalog.
 */
function extractRows(payload: unknown): unknown[] | undefined {
	if (Array.isArray(payload)) return payload;
	if (isRecord(payload)) {
		if (Array.isArray(payload.data)) return payload.data;
		if (Array.isArray(payload.models)) return payload.models;
	}
	return undefined;
}

/**
 * Parse one live model row, tolerating `snake_case` (Verboo's real payload)
 * and `camelCase` variants. Returns `undefined` when the row has no usable id.
 */
function parseLiveRow(row: unknown): LiveModelCapability | undefined {
	if (!isRecord(row)) return undefined;
	const id = asNonEmptyString(row.id);
	if (!id) return undefined;

	const capability: LiveModelCapability = { id };

	const contextWindow = asPositiveNumber(row.context_window ?? row.contextWindow);
	if (contextWindow !== undefined) capability.contextWindow = contextWindow;

	if (typeof row.vision === "boolean") capability.vision = row.vision;

	if (isRecord(row.reasoning)) {
		const effortLevels = asStringArray(row.reasoning.effort_levels ?? row.reasoning.effortLevels);
		const defaultEffort = asNonEmptyString(
			row.reasoning.default_effort ?? row.reasoning.defaultEffort,
		);
		if (effortLevels || defaultEffort) {
			capability.reasoning = {};
			if (effortLevels) capability.reasoning.effortLevels = effortLevels;
			if (defaultEffort) capability.reasoning.defaultEffort = defaultEffort;
		}
	}

	return capability;
}

export interface LiveModelsSnapshot {
	/** Raw rows exactly as received from `/models`, for auditable provenance. */
	rawRows: unknown[];
	/** Parsed, de-duplicated, order-preserving capability rows. */
	capabilities: LiveModelCapability[];
}

/**
 * Fetch `/models` and return BOTH the parsed capabilities and the raw rows
 * exactly as received, so a generator can persist an auditable snapshot.
 * Returns `undefined` on any failure — non-OK status, timeout, malformed or
 * empty body — with the same fallback contract as {@link listLiveModels}.
 */
export async function fetchLiveModelsSnapshot(
	options: LiveModelListOptions,
): Promise<LiveModelsSnapshot | undefined> {
	const { baseUrl, apiKey, timeoutMs = DEFAULT_MODELS_TIMEOUT_MS, fetchImpl = fetch } = options;

	const url = `${baseUrl.replace(/\/+$/, "")}/models`;
	const headers: Record<string, string> = { Accept: "application/json" };
	if (apiKey) headers.Authorization = `Bearer ${apiKey}`;

	const controller = new AbortController();
	const timeoutId = setTimeout(() => controller.abort(), timeoutMs);
	try {
		const response = await fetchImpl(url, { headers, signal: controller.signal });
		if (!response.ok) return undefined;

		const payload: unknown = await response.json();
		const rows = extractRows(payload);
		if (!rows) return undefined;

		const seen = new Set<string>();
		const capabilities: LiveModelCapability[] = [];
		for (const row of rows) {
			const capability = parseLiveRow(row);
			if (!capability || seen.has(capability.id)) continue;
			seen.add(capability.id);
			capabilities.push(capability);
		}

		// An empty live list is indistinguishable from "endpoint unusable":
		// prefer the generated catalog over an empty registration.
		if (capabilities.length === 0) return undefined;
		return { rawRows: rows, capabilities };
	} catch {
		return undefined;
	} finally {
		clearTimeout(timeoutId);
	}
}

/**
 * Fetch and parse live model capabilities from `{baseUrl}/models`.
 *
 * Returns `undefined` on any failure — non-OK status, timeout, malformed or
 * empty body — so callers fall back to the generated catalog instead of
 * failing startup. Rows are de-duplicated and order-preserving.
 */
export async function listLiveModels(
	options: LiveModelListOptions,
): Promise<LiveModelCapability[] | undefined> {
	return (await fetchLiveModelsSnapshot(options))?.capabilities;
}

/**
 * Build a conservative catalog entry for a live model with no generated
 * match. Capabilities are taken from the live row where present; `maxTokens`
 * stays at `UNKNOWN_MODEL_LIMITS.maxTokens` because Verboo publishes no
 * output cap (the conservative envelope is recorded in `notes`).
 */
export function entryFromLiveCapability(capability: LiveModelCapability): GeneratedModelEntry {
	// `reasoning` must reflect a USABLE effort list, not merely the presence of a
	// `reasoning` object. pi-ai treats an omitted `thinkingLevelMap` key as
	// SUPPORTED for every level except `xhigh`/`max`, so a live model that
	// declares `reasoning` but no `effort_levels` would otherwise be offered
	// levels Verboo does not accept. No efforts => reasoning false, off only
	// (conservative, honest).
	const map = thinkingLevelMapFromEfforts(capability.reasoning?.effortLevels);
	const reasoning = map !== undefined;

	return {
		id: capability.id,
		name: capability.id,
		reasoning,
		input: capability.vision ? ["text", "image"] : ["text"],
		cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
		contextWindow: capability.contextWindow ?? UNKNOWN_MODEL_LIMITS.contextWindow,
		maxTokens: UNKNOWN_MODEL_LIMITS.maxTokens,
		...(map ? { thinkingLevelMap: map } : {}),
		compat: { ...VERBOO_COMPAT },
		notes: [
			"Not present in the generated catalog: capabilities parsed from the live /models response, " +
				`maxTokens left at the conservative UNKNOWN_MODEL_LIMITS value (${UNKNOWN_MODEL_LIMITS.maxTokens}); ` +
				"Verboo publishes no output cap.",
		],
	};
}

export interface MergedCatalog {
	models: Model<"openai-completions">[];
	/** Live ids resolved against generated capability data. */
	matched: string[];
	/** Live ids kept with live/conservative capabilities (not in the generated catalog). */
	unknown: string[];
}

/**
 * Merge live capability rows with the generated capability catalog. A live id
 * with generated data keeps its generated capabilities; an uncatalogued live
 * id gets live-derived capabilities with conservative `maxTokens`.
 */
export function mergeLiveWithGenerated(
	live: readonly LiveModelCapability[],
	source: CatalogSource,
	generated: readonly GeneratedModelEntry[] = VERBOO_GENERATED_MODELS,
): MergedCatalog {
	const byId = new Map(generated.map((entry) => [entry.id, entry]));
	const models: Model<"openai-completions">[] = [];
	const matched: string[] = [];
	const unknown: string[] = [];

	for (const capability of live) {
		const entry = byId.get(capability.id);
		if (entry) {
			models.push(toModel(entry, source));
			matched.push(entry.id);
		} else {
			models.push(toModel(entryFromLiveCapability(capability), source));
			unknown.push(capability.id);
		}
	}

	return { models, matched, unknown };
}

export interface FetchModelsOptions {
	/** Bearer key for the live fetch, when one is already resolved. */
	apiKey?: string;
	timeoutMs?: number;
	/** Injectable for tests; defaults to global fetch. */
	fetchImpl?: typeof fetch;
}

export interface ResolvedCatalog {
	/** Live capabilities × generated data; the generated catalog when the live fetch fails. */
	models: Model<"openai-completions">[];
	/**
	 * Live ids from Verboo's `/models` endpoint when the fetch succeeded — the
	 * authoritative per-key list. `undefined` when the fetch failed and the
	 * generated fallback was used.
	 */
	liveIds: Set<string> | undefined;
	/** Allowlisted live ids kept with conservative capabilities (present only when liveIds is set). */
	unknownIds: string[];
}

/**
 * Resolve the effective catalog: live `/models` capabilities × generated
 * capability data. A successful live fetch is authoritative (it reflects
 * exactly what the key can use); failure degrades to the generated fallback so
 * startup is never blocked.
 */
export async function resolveCatalog(
	source: CatalogSource,
	options: FetchModelsOptions = {},
): Promise<ResolvedCatalog> {
	const baseline = baselineModels(source);
	try {
		const live = await listLiveModels({
			baseUrl: source.baseUrl,
			apiKey: options.apiKey,
			timeoutMs: options.timeoutMs,
			fetchImpl: options.fetchImpl,
		});
		if (!live) return { models: baseline, liveIds: undefined, unknownIds: [] };

		const merged = mergeLiveWithGenerated(live, source);
		return {
			models: merged.models,
			liveIds: new Set(live.map((row) => row.id)),
			unknownIds: merged.unknown,
		};
	} catch {
		return { models: baseline, liveIds: undefined, unknownIds: [] };
	}
}

/** Metadata of the generated fallback catalog, for diagnostics and docs. */
export function generatedCatalogMeta(): typeof GENERATED_CATALOG_META {
	return GENERATED_CATALOG_META;
}
