// This file is auto-generated by scripts/generate-catalog.ts
// Do not edit manually — run `bun run generate-catalog` to update.
//
// Source: https://code.verboo.ai/router/v1/models, fetched 2026-09-25T08:59:54.868Z
// Verboo returns { data: [...] } with context_window, vision and
// reasoning.effort_levels/default_effort per model. It does NOT return
// display_name, an output-token cap, or pricing: name is derived from id,
// maxTokens comes from scripts/manual-overrides.ts, and cost is zero
// (unknown, never invented). thinkingLevelMap is derived per model from that
// model's effort_levels by src/thinking-levels.ts.

import type { GeneratedModelEntry } from "./catalog.ts";

export const VERBOO_GENERATED_MODELS: readonly GeneratedModelEntry[] = [
	{
		"id": "deepseek-v4-flash",
		"name": "deepseek-v4-flash",
		"reasoning": true,
		"input": [
			"text"
		],
		"cost": {
			"input": 0,
			"output": 0,
			"cacheRead": 0,
			"cacheWrite": 0
		},
		"contextWindow": 1048576,
		"maxTokens": 65536,
		"thinkingLevelMap": {
			"off": null,
			"minimal": null,
			"low": null,
			"medium": null,
			"high": "high",
			"xhigh": null,
			"max": "max"
		},
		"compat": {
			"thinkingFormat": "openai",
			"supportsReasoningEffort": true,
			"supportsDeveloperRole": false,
			"maxTokensField": "max_tokens",
			"supportsFinishReason": true,
			"supportsUsageInStreaming": true
		},
		"notes": [
			"maxTokens 65536: conservative envelope, NOT a published cap — Verboo /models returns no output-token limit and the docs do not publish one. The probe measured 262144 accepted (scripts/probe-report.json, 2026-09-25). 65536 is the value the maintainer's working OpenCode config already uses; models.json modelOverrides remains the escape hatch."
		]
	},
	{
		"id": "deepseek-v4-flash-0731",
		"name": "deepseek-v4-flash-0731",
		"reasoning": true,
		"input": [
			"text"
		],
		"cost": {
			"input": 0,
			"output": 0,
			"cacheRead": 0,
			"cacheWrite": 0
		},
		"contextWindow": 1048576,
		"maxTokens": 65536,
		"thinkingLevelMap": {
			"off": null,
			"minimal": null,
			"low": "low",
			"medium": "medium",
			"high": "high",
			"xhigh": "xhigh",
			"max": "max"
		},
		"compat": {
			"thinkingFormat": "openai",
			"supportsReasoningEffort": true,
			"supportsDeveloperRole": false,
			"maxTokensField": "max_tokens",
			"supportsFinishReason": true,
			"supportsUsageInStreaming": true
		},
		"notes": [
			"maxTokens 65536: conservative envelope, NOT a published cap — Verboo /models returns no output-token limit and the docs do not publish one. The probe measured 262144 accepted (scripts/probe-report.json, 2026-09-25). 65536 is the value the maintainer's working OpenCode config already uses; models.json modelOverrides remains the escape hatch."
		]
	},
	{
		"id": "deepseek-v4.1-flash",
		"name": "deepseek-v4.1-flash",
		"reasoning": true,
		"input": [
			"text",
			"image"
		],
		"cost": {
			"input": 0,
			"output": 0,
			"cacheRead": 0,
			"cacheWrite": 0
		},
		"contextWindow": 1048576,
		"maxTokens": 65536,
		"thinkingLevelMap": {
			"off": null,
			"minimal": null,
			"low": "low",
			"medium": null,
			"high": "high",
			"xhigh": "xhigh",
			"max": "max"
		},
		"compat": {
			"thinkingFormat": "openai",
			"supportsReasoningEffort": true,
			"supportsDeveloperRole": false,
			"maxTokensField": "max_tokens",
			"supportsFinishReason": true,
			"supportsUsageInStreaming": true
		},
		"notes": [
			"maxTokens 65536: conservative envelope, NOT a published cap — Verboo /models returns no output-token limit and the docs do not publish one. The probe measured 262144 accepted (scripts/probe-report.json, 2026-09-25). 65536 is the value the maintainer's working OpenCode config already uses; models.json modelOverrides remains the escape hatch.",
			"Verboo /models reports vision:true for this model while the maintainer's working OpenCode config marked it text-only; the generated catalog follows Verboo (input includes image) and records the divergence for re-verification."
		]
	},
	{
		"id": "glm-5.3-flash",
		"name": "glm-5.3-flash",
		"reasoning": true,
		"input": [
			"text",
			"image"
		],
		"cost": {
			"input": 0,
			"output": 0,
			"cacheRead": 0,
			"cacheWrite": 0
		},
		"contextWindow": 1048576,
		"maxTokens": 65536,
		"thinkingLevelMap": {
			"off": null,
			"minimal": null,
			"low": "low",
			"medium": null,
			"high": "high",
			"xhigh": null,
			"max": "max"
		},
		"compat": {
			"thinkingFormat": "openai",
			"supportsReasoningEffort": true,
			"supportsDeveloperRole": false,
			"maxTokensField": "max_tokens",
			"supportsFinishReason": true,
			"supportsUsageInStreaming": true
		},
		"notes": [
			"maxTokens 65536: conservative envelope, NOT a published cap — Verboo /models returns no output-token limit and the docs do not publish one. The probe measured 262144 accepted (scripts/probe-report.json, 2026-09-25). 65536 is the value the maintainer's working OpenCode config already uses; models.json modelOverrides remains the escape hatch."
		]
	},
	{
		"id": "mimo-v2.5",
		"name": "mimo-v2.5",
		"reasoning": false,
		"input": [
			"text",
			"image"
		],
		"cost": {
			"input": 0,
			"output": 0,
			"cacheRead": 0,
			"cacheWrite": 0
		},
		"contextWindow": 1048576,
		"maxTokens": 65536,
		"compat": {
			"thinkingFormat": "openai",
			"supportsReasoningEffort": true,
			"supportsDeveloperRole": false,
			"maxTokensField": "max_tokens",
			"supportsFinishReason": true,
			"supportsUsageInStreaming": true
		},
		"notes": [
			"maxTokens 65536: conservative envelope, NOT a published cap — Verboo /models returns no output-token limit and the docs do not publish one. The probe measured 262144 accepted (scripts/probe-report.json, 2026-09-25). 65536 is the value the maintainer's working OpenCode config already uses; models.json modelOverrides remains the escape hatch.",
			"Verboo /models declares no reasoning object for this model, yet live chat completions emit reasoning_content; the catalog stays honest to /models (reasoning:false, no thinkingLevelMap, pi offers only 'off') and records the inconsistency."
		]
	},
	{
		"id": "qwen3.8-27b",
		"name": "qwen3.8-27b",
		"reasoning": true,
		"input": [
			"text",
			"image"
		],
		"cost": {
			"input": 0,
			"output": 0,
			"cacheRead": 0,
			"cacheWrite": 0
		},
		"contextWindow": 262144,
		"maxTokens": 65536,
		"thinkingLevelMap": {
			"off": "none",
			"minimal": null,
			"low": "low",
			"medium": "medium",
			"high": null,
			"xhigh": "xhigh",
			"max": null
		},
		"compat": {
			"thinkingFormat": "openai",
			"supportsReasoningEffort": true,
			"supportsDeveloperRole": false,
			"maxTokensField": "max_tokens",
			"supportsFinishReason": true,
			"supportsUsageInStreaming": true
		},
		"notes": [
			"maxTokens 65536: conservative envelope, NOT a published cap — Verboo /models returns no output-token limit and the docs do not publish one. The probe measured 262144 rejected upstream with 502 {\"error\":\"upstream unavailable\"} and 131072 accepted (scripts/probe-report.json, 2026-09-25). 65536 is the value the maintainer's working OpenCode config already uses; models.json modelOverrides remains the escape hatch."
		]
	}
];

export const GENERATED_CATALOG_META = {
	source: "https://code.verboo.ai/router/v1/models",
	fetchedAt: "2026-09-25T08:59:54.868Z",
	modelCount: 6,
	models: ["deepseek-v4-flash","deepseek-v4-flash-0731","deepseek-v4.1-flash","glm-5.3-flash","mimo-v2.5","qwen3.8-27b"],
	notes: [
	"name is derived from id: Verboo /models returns no display_name.",
	"compat is the measured gateway behavior recorded in scripts/probe-report.json (2026-09-25): thinkingFormat openai, supportsReasoningEffort true, supportsDeveloperRole false, maxTokensField max_tokens, supportsFinishReason true, supportsUsageInStreaming true.",
	"cost is {0,0,0,0} for every model: Verboo publishes no pricing in /models (unknown, never invented)."
],
} as const;
